[package]
name = "crc"
version = "1.4.0"
authors = ["mrhooray <ruihu.pvt@gmail.com>"]
description = "Rust implementation of CRC(32, 64) with support of various standards"
keywords = ["crc", "crc32", "crc64", "hash", "checksum"]
readme = "README.md"
repository = "https://github.com/mrhooray/crc-rs.git"
documentation = "http://mrhooray.github.io/crc-rs/crc/index.html"
license = "MIT"

[dependencies]
util = { path = "./src/util" }
build_const = { version = "0.2", default-features = false }

[build-dependencies]
util = { path = "./src/util" }
build_const = "0.2"

[features]
std = []
default = ["std"]
